#!/bin/bash
# This is Mike Bell's "quickupdate" script
# usage: ./quickupdate  

./checkout_uistate
git ci -a
git push origin master
git push origin dev
git push origin dev-dungeon
./update_dropbox
echo "quickupdate script successful :)"
