#!/bin/bash

echo "updating dropbox..."

#rsync -av --progress --bwlimit=20 ../project-a-ios /Users/Mike/Dropbox2/Dropbox/GG365\ Special/Mike\'s\ Folder2/.

# should do some checks to make sure dropbox folder isn't empty...
rsync -av --progress ../project-a-ios /Users/Mike/Dropbox2/Dropbox/GG365\ Special/Mike\'s\ Folder2/.

echo "dropbox update finished"
