//  EquipDefines.h
//  project-a-ios
//
//  Created by Mike Bell on 3/25/13.

typedef enum {
    EQUIPSLOT_T_HEAD,
    EQUIPSLOT_T_NECK,
    EQUIPSLOT_T_CHEST,
    EQUIPSLOT_T_LSHOULDER,
    EQUIPSLOT_T_RSHOULDER,
    EQUIPSLOT_T_BACK,
    EQUIPSLOT_T_LARM,
    EQUIPSLOT_T_RARM,
    EQUIPSLOT_T_LHAND,
    EQUIPSLOT_T_RHAND,
    EQUIPSLOT_T_LRING,
    EQUIPSLOT_T_RRING,
    EQUIPSLOT_T_WAIST,
    EQUIPSLOT_T_LLEG,
    EQUIPSLOT_T_RLEG,
    EQUIPSLOT_T_LFOOT,
    EQUIPSLOT_T_RFOOT,
    EQUIPSLOT_T_LARMTOOL,
    EQUIPSLOT_T_RARMTOOL,
    
} EquipSlot_t;